// angular/src/app/app.component.ts
import { Component } from '@angular/core';
import { AuthService } from './auth.service';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css']
})
export class AppComponent {

  constructor(private authService: AuthService) {
    this.user = this.authService._user;
    this.token = this.authService._token;
  }

  user;
  token;
  error;

  login(credentials) {
    // login user using authService.
   this.authService.login(credentials);
   this.user = this.authService._user;
   this.token = this.authService._token;
   this.error = this.authService._error;
  }

  logout() {
    this.authService.logout();
    this.user = this.authService._user;
    this.token = this.authService._token;
  }

  testApi() {
    this.authService.getResource('friends')
  }
}

<div class="container">

  <!-- Complete this markup for showing error upon unsuccessful login. -->


  <!-- Complete this markup for showing the status bar correctly, depending on whether or not the user is authenticated. -->
  <div class="status" *ngIf="token">
    <span>User ID: {{user.name}} </span>
    <button (click)="testApi()">Test API</button>
    <button (click)="logout()">Logout</button>
  </div>

  <!-- Add markup for showing the login form if the user is not authenticated. -->
  <div *ngIf="!token">
    <p *ngIf="error" class="error">Login credentials were incorrect!</p>
  <form
    (ngSubmit)="login(f.value)"
    #f="ngForm"
  >
    <div class="form-group">
      <label for="username"> Please enter your username</label>
      <input
        type="text"
        name="username"
        id="username"
        class="form-control"
        placeholder="Enter username..."

        ngModel
        #username="ngModel"

        required
      >
    </div>
    <div class="form-group">
      <label for="password"> Please enter your password</label>
      <input
        type="text"
        name="password"
        id="password"
        class="form-control"
        placeholder="Enter password..."

        ngModel
        #password="ngModel"

        required
        minlength="8"
      >
    </div>
  <button
  type="submit"
  [disabled]="!f.valid"
  >Log in</button>
  </form>
  </div>
</div>

// react/src/App.js
import React, { Component } from 'react';

import AuthService from './authService';
import Login from './Login';

class App extends Component {
    // get the initial state from AuthService. 
    state = AuthService.getAuthState();
    error = '';
    // ...

    login = (username, password) => {
        // login the user with the given credentials and update the component state upon success or failure respectively.
        AuthService.login({username, password})
            .then(() => {
                this.setState(AuthService.getAuthState());
            })
            .catch(error => {
                this.error = `${error}`;
                console.log(this.error);
            })
    };

    logout = () => {
        // logout the user and update the component with state given by AuthService.
        console.log('help');
        AuthService.logout()
            .then(console.log('hej'));

        this.setState(AuthService.getAuthState());
    };

    testApi() {
        // test access to a protected API route and log the results.

        AuthService.getResource('friends')
            .then((response) => {
                console.log('friends: ', response)
            })
            .catch(error => {
                console.log('error message: ', error)
            })
    }

    getState = () => {
        console.log(this.state);
    };


    // ...

    render() {
        // complete the JSX code below to show the proper markup depending on whether or not the user has been authenticated.

        return (
            this.state
            ?
                (
            <div className="container">



                <div className="status">
                    <span>User ID: {this.state.name || 'No user'} </span>
                    <button onClick={this.testApi}>Test API</button>
                    <button onClick={this.logout}>Logout</button>
                </div>
                <button onClick={this.getState}>Get State</button>
            </div>
                ) : (
                <div>
                    {this.error ? <p className="error">Invalid user credentials</p> : <p></p>}
                    <Login onLogin={this.login} />
                </div>

                )
        );
    }
}

export default App;
